### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by abc123xxx** [andyturtles/Tess4Windows#3]
Hallo,

ich kann keinen Login mehr mit Email and Password durchführen.

Die Fehlermeldung lautet:

Login failed: "Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt."

Grüße

**Comment by andyturtles** [comment]
Hi,

can you please send me a log file (logs-Folder) from where the error 
occured?

best regards

Andre

Am 07.10.2021 um 13:55 schrieb abc123xxx:

**Comment by abc123xxx** [comment]
[logs.zip](https://github.com/andyturtles/Tess4Windows/files/7309093/logs.zip)

**Comment by abc123xxx** [comment]
Habe Ihnen gerade den Log-Ordner gesendet.

Grüße

**Comment by andyturtles** [comment]
Hi,

vielen Dank.
Bitte die neueste Version (1.8) herunterladen und noch einmal probieren.
Ich denke ich habe den Fehler gefunden, Tesla hatte nochmal was am Login
verfahren verändert.

Viele Grüsse

Andre


Am 08.10.2021 um 08:47 schrieb abc123xxx:

**Comment by abc123xxx** [comment]
Hallo,
ich habe jetzt die Version 1.8 verwendet.

Der Zugriff funktioniert jetzt zwar wieder, allerdings gibt es jetzt einen Unterordner "json", welcher nun direkt im Verzeichnis der DLL's angelegt wird.

Dies war bisher wohl nicht so.
Ich habe die DLL's bei meinem Programm unter "Programme (x86)" liegen. Da haben Ihre DLL's keinen Zugriff, um darunter den Ordner "json" anzulegen.
Können Sie das wieder so ändern, wie es bisher war?

Viele Grüße

**Comment by andyturtles** [comment]
Hallo,

den Json Ordner gibt es schon sehr lange, ich glaube eigentlich schon
seit der ersten Version die auf Githhub war.
Im zweifel einfach von Hand anlegen und nur darauf Rechte vergeben.

Viele Grüsse

Andre


Am 10.10.2021 um 14:16 schrieb abc123xxx:

**Comment by abc123xxx** [comment]
Hallo,

ok habe ich gemacht mit der Rechtevergabe.
Es funktioniert jetzt alles.

Evtl. können Sie ja in einer der nächsten Versionen den "json"-Ordner einstellbar machen oder direkt in ProgramData verschieben.

Viele Grüße

**Comment by abc123xxx** [comment]
Hallo,

ich habe wieder ein Problem mit dem Login.

[logs.zip](https://github.com/andyturtles/Tess4Windows/files/7482424/logs.zip)

Viele Grüße

**Comment by andyturtles** [comment]
Hallo,

nutzt Du die aktuelle Version?

1.8 ?

Viele Grüsse

Andre



Am 05.11.2021 um 11:37 schrieb abc123xxx:

**Comment by abc123xxx** [comment]
Hallo,

ja die Benutze ich.

Gruß Bernd

**Comment by andyturtles** [comment]
Hi,

ja, sorry, da hat Tesla mal wieder was geändert... :(
Jetzt gehts bei mir auch nicht mehr.
So langsam macht das kein Spass mehr...

Ich hoffe ich finde ne Lösung.

Viele Grüsse
Andre

Am 07.11.2021 um 19:59 schrieb abc123xxx:

**Comment by abc123xxx** [comment]
Hier ist etwas aktuelles beschrieben, evtl. hilft das ja weiter...

https://tesla-info.com/tesla-token.php

Gruß Bernd

**Comment by cycl0ne** [comment]
Schon gefixt? Geht noch immer nicht.

**Comment by andyturtles** [comment]
Hi,
jetzt sollte es wieder gehen. Beschreibung beachten, ist leider ein wenig Umständlicher geworden.
Viele Grüsse
Andre

**Comment by mediaexplorer74** [comment]
> Hi, jetzt sollte es wieder gehen. Beschreibung beachten, ist leider ein wenig Umständlicher geworden. Viele Grüsse Andre

Wow, I found at now that you created Tess4Windows app (WPF).  Cool, I RnD it =) Do you have some fresh api token associated with real tesla car dashboard? ;) I promise not open any dore and not switch the car lights =)))) Joke!
Best wishes,
Andrey :)
