### ISSUE TITLE
Quellcode Version 2.2 fehlt?

### ISSUE THREAD

**Issue by dida79** [andyturtles/Tess4Windows#4]
Hi AndyTurtles,

kann es sein, dass der Quellcode der Version 2.2 identisch mit der Version 2.1 ist und nicht mit der Version 2.2 übereinstimmt?

LG Dida

**Comment by andyturtles** [comment]
Hi,
ja, ich hab vergessen die Änderung der Versionsnummer einzuchecken ;) (Hab ich gerade nachgeholt)
Sonst hat sich nichts an der Windows App geändert, die relevanten Änderungen sind im API Projekt. Das sollte aktuell sein.

Viele Grüsse
Andre
